/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* RedLED */
#define RedLED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define RedLED_0_INBUF_ENABLED 0u
#define RedLED_0_INIT_DRIVESTATE 1u
#define RedLED_0_INIT_MUXSEL 8u
#define RedLED_0_INPUT_SYNC 2u
#define RedLED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RedLED_0_NUM 3u
#define RedLED_0_PORT GPIO_PRT0
#define RedLED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define RedLED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define RedLED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define RedLED_INBUF_ENABLED 0u
#define RedLED_INIT_DRIVESTATE 1u
#define RedLED_INIT_MUXSEL 8u
#define RedLED_INPUT_SYNC 2u
#define RedLED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RedLED_NUM 3u
#define RedLED_PORT GPIO_PRT0
#define RedLED_SLEWRATE CY_GPIO_SLEW_FAST
#define RedLED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* BlueLED */
#define BlueLED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define BlueLED_0_INBUF_ENABLED 0u
#define BlueLED_0_INIT_DRIVESTATE 1u
#define BlueLED_0_INIT_MUXSEL 9u
#define BlueLED_0_INPUT_SYNC 2u
#define BlueLED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define BlueLED_0_NUM 1u
#define BlueLED_0_PORT GPIO_PRT11
#define BlueLED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define BlueLED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define BlueLED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define BlueLED_INBUF_ENABLED 0u
#define BlueLED_INIT_DRIVESTATE 1u
#define BlueLED_INIT_MUXSEL 9u
#define BlueLED_INPUT_SYNC 2u
#define BlueLED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define BlueLED_NUM 1u
#define BlueLED_PORT GPIO_PRT11
#define BlueLED_SLEWRATE CY_GPIO_SLEW_FAST
#define BlueLED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* GreenLED */
#define GreenLED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define GreenLED_0_INBUF_ENABLED 0u
#define GreenLED_0_INIT_DRIVESTATE 1u
#define GreenLED_0_INIT_MUXSEL 8u
#define GreenLED_0_INPUT_SYNC 2u
#define GreenLED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define GreenLED_0_NUM 1u
#define GreenLED_0_PORT GPIO_PRT1
#define GreenLED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define GreenLED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define GreenLED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define GreenLED_INBUF_ENABLED 0u
#define GreenLED_INIT_DRIVESTATE 1u
#define GreenLED_INIT_MUXSEL 8u
#define GreenLED_INPUT_SYNC 2u
#define GreenLED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define GreenLED_NUM 1u
#define GreenLED_PORT GPIO_PRT1
#define GreenLED_SLEWRATE CY_GPIO_SLEW_FAST
#define GreenLED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* mI2C_scl */
#define mI2C_scl_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define mI2C_scl_0_INBUF_ENABLED 1u
#define mI2C_scl_0_INIT_DRIVESTATE 1u
#define mI2C_scl_0_INIT_MUXSEL 19u
#define mI2C_scl_0_INPUT_SYNC 2u
#define mI2C_scl_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mI2C_scl_0_NUM 0u
#define mI2C_scl_0_PORT GPIO_PRT6
#define mI2C_scl_0_SLEWRATE CY_GPIO_SLEW_FAST
#define mI2C_scl_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define mI2C_scl_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define mI2C_scl_INBUF_ENABLED 1u
#define mI2C_scl_INIT_DRIVESTATE 1u
#define mI2C_scl_INIT_MUXSEL 19u
#define mI2C_scl_INPUT_SYNC 2u
#define mI2C_scl_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mI2C_scl_NUM 0u
#define mI2C_scl_PORT GPIO_PRT6
#define mI2C_scl_SLEWRATE CY_GPIO_SLEW_FAST
#define mI2C_scl_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* mI2C_sda */
#define mI2C_sda_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define mI2C_sda_0_INBUF_ENABLED 1u
#define mI2C_sda_0_INIT_DRIVESTATE 1u
#define mI2C_sda_0_INIT_MUXSEL 19u
#define mI2C_sda_0_INPUT_SYNC 2u
#define mI2C_sda_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mI2C_sda_0_NUM 1u
#define mI2C_sda_0_PORT GPIO_PRT6
#define mI2C_sda_0_SLEWRATE CY_GPIO_SLEW_FAST
#define mI2C_sda_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define mI2C_sda_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define mI2C_sda_INBUF_ENABLED 1u
#define mI2C_sda_INIT_DRIVESTATE 1u
#define mI2C_sda_INIT_MUXSEL 19u
#define mI2C_sda_INPUT_SYNC 2u
#define mI2C_sda_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mI2C_sda_NUM 1u
#define mI2C_sda_PORT GPIO_PRT6
#define mI2C_sda_SLEWRATE CY_GPIO_SLEW_FAST
#define mI2C_sda_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* sI2C_scl */
#define sI2C_scl_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define sI2C_scl_0_INBUF_ENABLED 1u
#define sI2C_scl_0_INIT_DRIVESTATE 1u
#define sI2C_scl_0_INIT_MUXSEL 19u
#define sI2C_scl_0_INPUT_SYNC 2u
#define sI2C_scl_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define sI2C_scl_0_NUM 0u
#define sI2C_scl_0_PORT GPIO_PRT9
#define sI2C_scl_0_SLEWRATE CY_GPIO_SLEW_FAST
#define sI2C_scl_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define sI2C_scl_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define sI2C_scl_INBUF_ENABLED 1u
#define sI2C_scl_INIT_DRIVESTATE 1u
#define sI2C_scl_INIT_MUXSEL 19u
#define sI2C_scl_INPUT_SYNC 2u
#define sI2C_scl_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define sI2C_scl_NUM 0u
#define sI2C_scl_PORT GPIO_PRT9
#define sI2C_scl_SLEWRATE CY_GPIO_SLEW_FAST
#define sI2C_scl_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* sI2C_sda */
#define sI2C_sda_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define sI2C_sda_0_INBUF_ENABLED 1u
#define sI2C_sda_0_INIT_DRIVESTATE 1u
#define sI2C_sda_0_INIT_MUXSEL 19u
#define sI2C_sda_0_INPUT_SYNC 2u
#define sI2C_sda_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define sI2C_sda_0_NUM 1u
#define sI2C_sda_0_PORT GPIO_PRT9
#define sI2C_sda_0_SLEWRATE CY_GPIO_SLEW_FAST
#define sI2C_sda_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define sI2C_sda_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define sI2C_sda_INBUF_ENABLED 1u
#define sI2C_sda_INIT_DRIVESTATE 1u
#define sI2C_sda_INIT_MUXSEL 19u
#define sI2C_sda_INPUT_SYNC 2u
#define sI2C_sda_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define sI2C_sda_NUM 1u
#define sI2C_sda_PORT GPIO_PRT9
#define sI2C_sda_SLEWRATE CY_GPIO_SLEW_FAST
#define sI2C_sda_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
